### ISSUE TITLE
Unable to build font with current source

### ISSUE THREAD

**Issue by thundernixon** [rsms/inter#229]
**Expected behavior**

I am trying to build VF and static fonts for Google Fonts for the PR at https://github.com/google/fonts/pull/1908. For this PR, I ultimately need to build:
- Inter Variable (Roman & Italic)
- Static TTFs

**Describe the bug**

The big issue: I am unable to build anything currently, as it is failing to generate UFOs.

Possibly related I noticed in recent builds, the name IDs 3 & 5 of my built fonts lacked a git hash, as they do have in in the latest release, `Inter-V.otf`. In https://github.com/rsms/inter/issues/202 from October, this is cited as an issue caused by a change in FontMake. 

It seems that the solution at the time was to remove FontMake from the setup, based on commit " fontbuild: remove use of fontmake, simplifying things." ([builder.py at `06b166889`](https://github.com/rsms/inter/blob/06b166889e335a2454c0767734a05b27f6403098/misc/fontbuildlib/builder.py)).

However, now that the Thin masters have been upgraded with https://github.com/rsms/inter/pull/219, I cannot build the project (not sure whether these two things are related, but I want to make sure to build with the upgrades).

It's possible I'm just doing something wrong.

**To Reproduce**
1. Go to the latest state of `master` (maybe even by cloning a new repo, as I have tried)
2. Run `init.sh`
3. Try to run `misc/googlefonts/build.sh --clean`, or even just the simpler `make build/fonts/var/Inter.var.otf`

**Environment**
- OS: macOS 10.15.2
- commit: 06b166889e3

**Additional context**

On my first run, I'm finding that the Inter.glyphs file has a duplicate layer name, so I fix that.

<details>
<summary><b><code>$ misc/googlefonts/build.sh --clean</code></b> (Click to expand)</summary>

```
misc/fontbuild glyphsync -o build/ufo src/Inter.glyphs
generating build/ufo/Inter.designspace from src/Inter.glyphs
Inter Thin: Glyph asterisk, layer Dec 27 18, 16:33: Duplicate glyph layer name
Traceback (most recent call last):
  File "misc/fontbuild", line 623, in <module>
    Main().main(sys.argv)
  File "misc/fontbuild", line 127, in main
    getattr(self, cmd)(argv[i:])
  File "misc/fontbuild", line 375, in cmd_glyphsync
    minimize_glyphs_diffs=True,
  File "/Users/stephennixon/type-repos/google-font-repos/inter/build/venv/lib/python3.7/site-packages/glyphsLib/builder/__init__.py", line 111, in to_designspace
    return builder.designspace
  File "/Users/stephennixon/type-repos/google-font-repos/inter/build/venv/lib/python3.7/site-packages/glyphsLib/builder/builders.py", line 260, in designspace
    list(self.masters)  # Make sure that the UFOs are built
  File "/Users/stephennixon/type-repos/google-font-repos/inter/build/venv/lib/python3.7/site-packages/glyphsLib/builder/builders.py", line 223, in masters
    self.to_ufo_glyph(ufo_glyph, layer, layer.parent)
  File "/Users/stephennixon/type-repos/google-font-repos/inter/build/venv/lib/python3.7/site-packages/glyphsLib/builder/glyph.py", line 127, in to_ufo_glyph
    self.to_ufo_glyph_background(ufo_glyph, layer)
  File "/Users/stephennixon/type-repos/google-font-repos/inter/build/venv/lib/python3.7/site-packages/glyphsLib/builder/glyph.py", line 265, in to_ufo_glyph_background
    new_glyph = ufo_layer.newGlyph(glyph.name)
  File "/Users/stephennixon/type-repos/google-font-repos/inter/build/venv/lib/python3.7/site-packages/ufoLib2/objects/layer.py", line 120, in newGlyph
    raise KeyError("glyph %r already exists" % name)
KeyError: "glyph 'asterisk' already exists"
make: *** [build/ufo/Inter.designspace] Error 1
```
</details>

The `asterisk` glyph had the layer `“Dec 27 18, 16:33”`twice. So, I changed one of the layer names to “Dec 27 18, 16:34” and ran it again.

Here's the traceback I get from trying to build this time:

<details>
<summary><b><code>$ misc/googlefonts/build.sh --clean</code></b> (Click to expand)</summary>

```
Generating 'build/etc/generated.make'
misc/fontbuild glyphsync -o build/ufo src/Inter.glyphs
generating build/ufo/Inter.designspace from src/Inter.glyphs
Instance user-space location (400) redefined by 'Regular'
Process Process-1:
Process Process-2:
Process Process-3:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "misc/fontbuild", line 238, in _glyphsyncWriteUFO
    setFontInfo(font, weight)
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/misc/fontbuildlib/info.py", line 94, in setFontInfo
    updateFontVersion(font, dummy=True, isVF=False)
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/misc/fontbuildlib/info.py", line 47, in updateFontVersion
    font.info.version = version
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "misc/fontbuild", line 238, in _glyphsyncWriteUFO
    setFontInfo(font, weight)
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/misc/fontbuildlib/info.py", line 94, in setFontInfo
    updateFontVersion(font, dummy=True, isVF=False)
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/misc/fontbuildlib/info.py", line 47, in updateFontVersion
    font.info.version = version
AttributeError: 'Info' object has no attribute 'version'
AttributeError: 'Info' object has no attribute 'version'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "misc/fontbuild", line 238, in _glyphsyncWriteUFO
    setFontInfo(font, weight)
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/misc/fontbuildlib/info.py", line 94, in setFontInfo
    updateFontVersion(font, dummy=True, isVF=False)
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/misc/fontbuildlib/info.py", line 47, in updateFontVersion
    font.info.version = version
AttributeError: 'Info' object has no attribute 'version'
Process Process-4:
Process Process-5:
write build/ufo/Inter.designspace
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
Process Process-6:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "misc/fontbuild", line 238, in _glyphsyncWriteUFO
    setFontInfo(font, weight)
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/misc/fontbuildlib/info.py", line 94, in setFontInfo
    updateFontVersion(font, dummy=True, isVF=False)
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/misc/fontbuildlib/info.py", line 47, in updateFontVersion
    font.info.version = version
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
AttributeError: 'Info' object has no attribute 'version'
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "misc/fontbuild", line 238, in _glyphsyncWriteUFO
    setFontInfo(font, weight)
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/misc/fontbuildlib/info.py", line 94, in setFontInfo
    updateFontVersion(font, dummy=True, isVF=False)
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/misc/fontbuildlib/info.py", line 47, in updateFontVersion
    font.info.version = version
AttributeError: 'Info' object has no attribute 'version'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "misc/fontbuild", line 238, in _glyphsyncWriteUFO
    setFontInfo(font, weight)
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/misc/fontbuildlib/info.py", line 94, in setFontInfo
    updateFontVersion(font, dummy=True, isVF=False)
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/misc/fontbuildlib/info.py", line 47, in updateFontVersion
    font.info.version = version
AttributeError: 'Info' object has no attribute 'version'
write build/ufo/Inter-roman.designspace
write build/ufo/Inter-italic.designspace
touch "build/ufo/Inter-Thin.ufo"
touch "build/ufo/Inter-ThinItalic.ufo"
touch "build/ufo/Inter-Regular.ufo"
touch "build/ufo/Inter-Italic.ufo"
touch "build/ufo/Inter-Black.ufo"
touch "build/ufo/Inter-BlackItalic.ufo"
misc/fontbuild compile-var -o build/fonts/var/Inter.var.otf  build/ufo/Inter.designspace
Traceback (most recent call last):
  File "misc/fontbuild", line 623, in <module>
    Main().main(sys.argv)
  File "misc/fontbuild", line 127, in main
    getattr(self, cmd)(argv[i:])
  File "misc/fontbuild", line 155, in cmd_compile_var
    FontBuilder().buildVariable(args.srcfile, outfilename)
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/misc/fontbuildlib/builder.py", line 55, in buildVariable
    designspace = self._loadDesignspace(designspace)
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/misc/fontbuildlib/builder.py", line 98, in _loadDesignspace
    masters = designspace.loadSourceFonts(opener=Font)
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/lib/python3.7/site-packages/fontTools/designspaceLib/__init__.py", line 1321, in loadSourceFonts
    source.font = opener(source.path, **kwargs)
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/lib/python3.7/site-packages/defcon/objects/font.py", line 148, in __init__
    reader = UFOReader(self._path, validate=self.ufoLibReadValidate)
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/lib/python3.7/site-packages/fontTools/ufoLib/__init__.py", line 208, in __init__
    structure = _sniffFileStructure(path)
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/lib/python3.7/site-packages/fontTools/ufoLib/__init__.py", line 1595, in _sniffFileStructure
    "The specified UFO does not have a known structure: '%s'" % ufo_path
fontTools.ufoLib.errors.UFOLibError: The specified UFO does not have a known structure: '/Users/stephennixon/type-repos/google-font-repos/inter2/build/ufo/Inter-Thin.ufo'
make: *** [build/fonts/var/Inter.var.otf] Error 1
```
</details>

It's worth noting that there also seems to be an issue with the features in Inter Thin. It's buried in the output in the build command above, but more clear if I directly try to use FontMake (version `2.0.8`):

<details>
<summary><b><code>$ fontmake -o variable -g src/Inter.glyphs </code></b> (Click to expand)</summary>

```         
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.classes:Parsing "src/Inter.glyphs" file into <GSFont>
WARNING:glyphsLib.builder.axes:Instance user-space location (400) redefined by 'Regular'
INFO:fontmake.font_project:Building variable font variable_ttf/Inter-VF.ttf
INFO:ufo2ft:Pre-processing glyphs
INFO:cu2qu.ufo:New spline lengths: 1: 3, 2: 2111, 3: 1942, 4: 416, 5: 27, 6: 7
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on Inter-Thin
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on Inter-ThinItalic
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on Inter-Regular
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on Inter-Italic
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on Inter-Black
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on Inter-BlackItalic
INFO:ufo2ft:Building OpenType tables for Inter-Thin
Traceback (most recent call last):
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/lib/python3.7/site-packages/fontTools/feaLib/lexer.py", line 234, in __next__
    self.lexers_.append(self.make_lexer_(path))
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/lib/python3.7/site-packages/fontTools/feaLib/lexer.py", line 251, in make_lexer_
    fileobj = open(filename, "r", encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/stephennixon/type-repos/google-font-repos/inter2/master_ufo/features/ccmp.fea'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/bin/fontmake", line 8, in <module>
    sys.exit(main())
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/lib/python3.7/site-packages/fontmake/__main__.py", line 425, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/lib/python3.7/site-packages/fontmake/font_project.py", line 672, in run_from_glyphs
    self.run_from_designspace(designspace_path, **kwargs)
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/lib/python3.7/site-packages/fontmake/font_project.py", line 896, in run_from_designspace
    **kwargs,
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/lib/python3.7/site-packages/fontmake/font_project.py", line 962, in _run_from_designspace_interpolatable
    designspace, output_path=output_path, output_dir=output_dir, **kwargs
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/lib/python3.7/site-packages/fontmake/font_project.py", line 310, in build_variable_font
    inplace=True,
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/lib/python3.7/site-packages/ufo2ft/__init__.py", line 571, in compileVariableTTF
    debugFeatureFile=debugFeatureFile,
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/lib/python3.7/site-packages/ufo2ft/__init__.py", line 398, in compileInterpolatableTTFsFromDS
    for source, ttf in zip(result.sources, ttfs):
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/lib/python3.7/site-packages/ufo2ft/__init__.py", line 307, in compileInterpolatableTTFs
    debugFeatureFile=debugFeatureFile,
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/lib/python3.7/site-packages/ufo2ft/__init__.py", line 521, in compileFeatures
    otFont = featureCompiler.compile()
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/lib/python3.7/site-packages/ufo2ft/featureCompiler.py", line 120, in compile
    self.setupFeatures()
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/lib/python3.7/site-packages/ufo2ft/featureCompiler.py", line 215, in setupFeatures
    featureFile = parseLayoutFeatures(self.ufo)
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/lib/python3.7/site-packages/ufo2ft/featureCompiler.py", line 43, in parseLayoutFeatures
    doc = parser.parse()
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/lib/python3.7/site-packages/fontTools/feaLib/parser.py", line 73, in parse
    statements.append(self.parse_feature_block_())
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/lib/python3.7/site-packages/fontTools/feaLib/parser.py", line 1245, in parse_feature_block_
    cv_feature)
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/lib/python3.7/site-packages/fontTools/feaLib/parser.py", line 1372, in parse_block_
    self.expect_symbol_("{")
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/lib/python3.7/site-packages/fontTools/feaLib/parser.py", line 1540, in expect_symbol_
    self.advance_lexer_()
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/lib/python3.7/site-packages/fontTools/feaLib/parser.py", line 1605, in advance_lexer_
    self.next_token_location_) = next(self.lexer_)
  File "/Users/stephennixon/type-repos/google-font-repos/inter2/build/venv/lib/python3.7/site-packages/fontTools/feaLib/lexer.py", line 239, in __next__
    raise IncludedFeaNotFound(fname_token, fname_location)
fontTools.feaLib.error.IncludedFeaNotFound: /Users/stephennixon/type-repos/google-font-repos/inter2/master_ufo/Inter-Thin.ufo:73:8: features/ccmp.fea
```

</details>

**Comment by rsms** [comment]
Looking into this now. My first attempt to repro this failed (i.e. it builds successfully for me)

```bash
$ cd src/inter
$ rm -rf build/fonts build/ufo
$ ./init.sh
Generating 'build/etc/generated.make'
$ misc/googlefonts/build.sh --clean
misc/fontbuild glyphsync -o build/ufo src/Inter.glyphs
generating build/ufo/Inter.designspace from src/Inter.glyphs
Instance user-space location (400) redefined by 'Regular'
write build/ufo/Inter.designspace
write build/ufo/Inter-ThinItalic.ufo
write build/ufo/Inter-Italic.ufo
write build/ufo/Inter-Thin.ufo
write build/ufo/Inter-BlackItalic.ufo
write build/ufo/Inter-Regular.ufo
write build/ufo/Inter-Black.ufo
write build/ufo/Inter-roman.designspace
write build/ufo/Inter-italic.designspace
touch "build/ufo/Inter-Thin.ufo"
misc/fontbuild compile-var -o build/fonts/var/Inter.var.otf  build/ufo/Inter.designspace
write build/fonts/var/Inter.var.otf
$
```

This is a clean build of rsms/inter@06b166889e335a2454c0767734a05b27f6403098 (current master & HEAD in git on github as I’m writing this.)

@thundernixon Could you try deleting your Python virtual env and initializing it again?

```bash
rm -rf build/venv && ./init.sh
```

Also could you try running the following two commands and sharing the output:

```
$ shasum src/Inter.glyphs misc/fontbuild
$ git rev-parse HEAD
```

Output for these commands for me: (your should match exactly)

```
$ shasum src/Inter.glyphs misc/fontbuild
ac595edd6af33de3d947dedc5ec1a302b2d40edf  src/Inter.glyphs
952369d1ff1a95375ba30e34b832073d02bb4e1f  misc/fontbuild
$ git rev-parse HEAD
06b166889e335a2454c0767734a05b27f6403098
```

Another thing to try is a clean glyphsync run in debug mode:

```
$ mkdir -p build/ufo-test
$ ( . init.sh ; ./misc/fontbuild --debug glyphsync -o build/ufo-test src/Inter.glyphs )
```

**Comment by rsms** [comment]
Another thing to try is a clean checkout. I just tried this on my machine:

```
$ git clone git@github.com:rsms/inter.git tmp-inter
$ cd tmp-inter
$ misc/googlefonts/build.sh --clean
```

Which succeeded. System info for me:

```
$ uname -rsv
Darwin 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64
$ python --version
Python 3.7.5
$ python3 --version
Python 3.7.5
```

**Comment by thundernixon** [comment]
Hey, thanks so much for all this help!

I'm slightly embarrassed but quite happy to say that after this:

```
$ rm -rf build/fonts build/ufo venv
$ ./init.sh
```

...it built just as expected. This slightly confuses me, as I _did_ make a temp, clean download earlier, and ran init. For me, `$ python --version` yields `Python 2.7.16`, so perhaps this could be to blame... this is just the default macOS setup I have. Do you recommend changing it? I feel like maybe I've heard advice in both directions, in the past.

If the other info would still be helpful:

```
▶ shasum src/Inter.glyphs misc/fontbuild
ac595edd6af33de3d947dedc5ec1a302b2d40edf  src/Inter.glyphs
952369d1ff1a95375ba30e34b832073d02bb4e1f  misc/fontbuild
                                                                                                       
▶ git rev-parse HEAD
877166dddae5b93c62d6a526a941f1e91f63aba3

▶ uname -rsv
Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64
```
(I'm on a `qa` branch, so the different hash for `HEAD` is expected).

**Comment by rsms** [comment]
It all sounds good (your details.) The init.sh script will look for `python3` as well as `python` so you likely have python 3 installed as python3 which is totally fine. No need to make any changes.

My guess to what happened was changes to the UFOs in the build folder. It’s strange though since `make clean` removes `build/ufo` (but not `build/venv` so maybe that was the issue.)

Anyhow, glad you were able to resolve it!

**Comment by thundernixon** [comment]
Good to know!

Yeah, I’m slightly confused about why it worked after the extra round of troubleshooting, when it seemed stuck before. Must have just needed to step away and approach it cleanly.

Thanks for your help!
