### ISSUE TITLE
init.sh fails on Arch Linux

### ISSUE THREAD

**Issue by 190n** [rsms/inter#444]
**Describe the bug**
I'm trying to build the font from source on Linux. `init.sh` is able to install several dependencies, but it fails on `skia-pathops`.

**To Reproduce**
1. Clone the repository
2. Run `./init.sh`

**Expected behavior**
All prerequisites are installed and I can run `make`.

**Screenshots**
<details>
<summary>Relevant output</summary>
<pre>
Building wheels for collected packages: skia-pathops
  Building wheel for skia-pathops (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ben/Downloads/inter/build/venv/bin/python /home/ben/Downloads/inter/build/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpxwy_fnaf
       cwd: /tmp/pip-install-czxmnow9/skia-pathops_bdbf4b199301473d8a67415e83a6e8a7
  Complete output (69 lines):
  running bdist_wheel
  running build
  running build_py
  running build_ext
  building 'pathops._pathops' extension
  building 'skia' library
  AttributeError: DistutilsMetaFinder instance has no attribute 'find_module'
  Traceback (most recent call last):
    File "/home/ben/Downloads/inter/build/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/ben/Downloads/inter/build/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/ben/Downloads/inter/build/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-fldop135/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 244, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-fldop135/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-fldop135/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 281, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-fldop135/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 367, in <module>
      setup(**setup_params)
    File "/tmp/pip-build-env-fldop135/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 155, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-fldop135/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
      return run_commands(dist)
    File "/tmp/pip-build-env-fldop135/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-fldop135/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-fldop135/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-fldop135/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/tmp/pip-build-env-fldop135/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-fldop135/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-fldop135/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/tmp/pip-build-env-fldop135/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-fldop135/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "setup.py", line 216, in run
      build_ext.run(self)
    File "/tmp/pip-build-env-fldop135/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/tmp/pip-build-env-fldop135/overlay/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "/tmp/pip-build-env-fldop135/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/tmp/pip-build-env-fldop135/overlay/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
      _build_ext.build_ext.build_extensions(self)
    File "/tmp/pip-build-env-fldop135/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/tmp/pip-build-env-fldop135/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "setup.py", line 194, in build_extension
      libraries=self.get_libraries(ext),
    File "setup.py", line 210, in get_libraries
      library_dir = self._library_builders[library](self.build_temp)
    File "setup.py", line 269, in build_skia
      subprocess.run(build_cmd, check=True, env=env)
    File "/usr/lib/python3.10/subprocess.py", line 524, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['python2', 'src/cpp/skia-builder/build_skia.py', 'build/temp.linux-x86_64-3.10/src/cpp/skia-builder/skia']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for skia-pathops
Failed to build skia-pathops
ERROR: Could not build wheels for skia-pathops, which is required to install pyproject.toml-based projects
WARNING: You are using pip version 21.3.1; however, version 22.0.4 is available.
You should consider upgrading via the '/home/ben/Downloads/inter/build/venv/bin/python -m pip install --upgrade pip' command.
</pre>
</details>

I still had the same issue after upgrading pip within the venv, as suggested.

**Environment**
- OS: Arch Linux
- App that renders the font: N/A
- Version of font: git master (7b4e19f9a)

**Additional context**

**Comment by rsms** [comment]
Thanks for the report. Only macOS is "officially" supported. PRs welcome for Linux support. However in this case I believe it's an issue with that specific Python package as it fails on macos aarch64 as well. I've pushed an update that upgrades skia-pathops — please try with cce4f42aca53a99973bcc89408f9836ebf57a811
