### ISSUE TITLE
Auto-hinting introduces an extra glyph, which causes variation breakage

### ISSUE THREAD

**Issue by jfkthame** [rsms/inter#75]
The "hinted" version of the variable TTF is broken, as a result of the spurious ".ttfautohint" glyph that is added by the auto-hinting process. This results in a glyph count mismatch with the 'gvar' table, which is an OpenType spec violation and will fail in environments where font tables are validated before use (e.g. Firefox).

As a result, the variations for Inter UI don't work in Firefox on https://v-fonts.com, where the "hinted" version is deployed. The Web Console in Firefox reports errors when loading the InterUI font resource:

```
downloadable font: gvar: Glyph count mismatch (font-family: "Inter UI" style:normal weight:400 stretch:100 src index:0) source: https://v-fonts.com/assets/fonts/Inter-UI.var.woff2 unknown:28:11
downloadable font: Dropping all Variation tables (font-family: "Inter UI" style:normal weight:400 stretch:100 src index:0) source: https://v-fonts.com/assets/fonts/Inter-UI.var.woff2 unknown:28:11
downloadable font: fvar: Discarding Variations table (font-family: "Inter UI" style:normal weight:400 stretch:100 src index:0) source: https://v-fonts.com/assets/fonts/Inter-UI.var.woff2 unknown:28:11
downloadable font: Table discarded (font-family: "Inter UI" style:normal weight:400 stretch:100 src index:0) source: https://v-fonts.com/assets/fonts/Inter-UI.var.woff2 unknown:28:11
downloadable font: gvar: Discarding Variations table (font-family: "Inter UI" style:normal weight:400 stretch:100 src index:0) source: https://v-fonts.com/assets/fonts/Inter-UI.var.woff2 unknown:28:11
downloadable font: Table discarded (font-family: "Inter UI" style:normal weight:400 stretch:100 src index:0) source: https://v-fonts.com/assets/fonts/Inter-UI.var.woff2 unknown:28:11
```

Similarly, attempting to decompile the file using TTX results in failure in the 'gvar' table:

```
Dumping "/Users/jkew/Downloads/Inter-UI-3/Inter UI (TTF variable hinted)/Inter-UI.var.ttf" to "/Users/jkew/Downloads/Inter-UI-3/Inter UI (TTF variable hinted)/Inter-UI.var.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
Dumping 'cmap' table...
Dumping 'fpgm' table...
Dumping 'prep' table...
Dumping 'cvt ' table...
Dumping 'loca' table...
Dumping 'glyf' table...
Dumping 'name' table...
Dumping 'post' table...
Dumping 'gasp' table...
Dumping 'GDEF' table...
Dumping 'GPOS' table...
Dumping 'GSUB' table...
Dumping 'HVAR' table...
Dumping 'MVAR' table...
Dumping 'STAT' table...
Dumping 'fvar' table...
ERROR: An exception occurred during the decompilation of the 'gvar' table
Traceback (most recent call last):
  File "/usr/local/Cellar/fonttools/3.26.0/libexec/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 391, in __getitem__
    table.decompile(data, self)
  File "/usr/local/Cellar/fonttools/3.26.0/libexec/lib/python2.7/site-packages/fontTools/ttLib/tables/_g_v_a_r.py", line 98, in decompile
    assert len(glyphs) == self.glyphCount
AssertionError
Dumping 'gvar' table...
```

The unhinted version of the font does not have this problem. Inspecting the hinted version shows that a new glyph named ".ttfautohint" has appeared, which is resulting in the mismatch with the (unchanged) 'gvar' table.

See https://docs.microsoft.com/en-us/typography/opentype/spec/gvar#gvar-header, where the `glyphCount` field is documented as:

Type | Name | Description
-- | -- | --
uint16 | glyphCount | The number of glyphs in this font. This must match the number of glyphs stored elsewhere in the font.

This requirement is broken by the addition of the autohint glyph.

**Comment by rsms** [comment]
First off, thank you for an excellent bug report.

It seems that there's currently no support for variable fonts in the latest official release of ttfautohint. http://repo.or.cz/ttfautohint.git/refs lists a "vf" branch, but it's stale (10mo old.) Dave C mentions a fork with vf support at https://gitlab.com/ewaldhew/tah-vf/tree/gvar-wip in this conversation https://groups.google.com/forum/#!topic/googlefonts-discuss/WJX1lrzcwVs though there has been no activity in the last two months and the project seems to be at an early stage.

I'll remove hinted VF for now in the distribution. One day when ttfautohint supports VF we can make a hinted build again. Alternatively if we can figure out a different way to add TTF hinting programs.

Thank you for catching this!

**Comment by rsms** [comment]
FYI: RC 2 released: https://github.com/rsms/inter/releases/tag/v3.0-rc2
